

const newsList = [
  {
    id: 1,
    category: "Covid",
    type: "news",
    caption: "Korona vaka sayısı",
    summary: "Türkiyede vaka sayısı azalıyor.",
    imgPath: "https://via.placeholder.com/600x300?text=KORONA",
    imgAlt: "test haber img",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi at nisi ex. Nullam et elit elementum, consequat risus ut, aliquet metus. Phasellus pharetra, urna non mollis auctor, dui erat fermentum lorem, sed egestas sem nisl ut augue. Duis vitae turpis non dui luctus congue. Donec iaculis, diam in consequat dapibus, tortor mauris rhoncus ex, sit amet rutrum augue arcu a lacus. Vestibulum porta, orci vitae ultrices blandit, dolor metus tristique lorem,eget placerat nisl nulla in turpis. Maecenas vel aliquam leo. Vivamus eleifend sapien vel mauris mollis imperdiet.",
    subjects: ["Covid", "Türkiye"],
    authors: ["Mustafa Çolakoğlu", "Burak Kalafat"],
    createdDate: "2020-04-23T18:25:43.511Z",
    updateDate: "2020-05-01T14:35:43.511Z",
    expressDate: "2020-05-01T14:35:43.511Z",
    priority: 1,
    isActive: true,
  },
  {
    id: 2,
    category: "Libya",
    type: "news",
    caption: "Libya'da Hafter milislerine ikmal yapan yakıt tankeri ile iki askeri araç vuruldu",
    summary: "Libya karışık aga",
    imgPath: "https://via.placeholder.com/600x300?text=LİBYA",
    imgAlt: "test haber img",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi at nisi ex. Nullam et elit elementum, consequat risus ut, aliquet metus. Phasellus pharetra, urna non mollis auctor, dui erat fermentum lorem, sed egestas sem nisl ut augue. Duis vitae turpis non dui luctus congue. Donec iaculis, diam in consequat dapibus, tortor mauris rhoncus ex, sit amet rutrum augue arcu a lacus. Vestibulum porta, orci vitae ultrices blandit, dolor metus tristique lorem, eget placerat nisl nulla in turpis. Maecenas vel aliquam leo. Vivamus eleifend sapien vel mauris mollis imperdiet.",
    subjects: ["Covid", "Türkiye"],
    authors: ["Mustafa Çolakoğlu", "Burak Kalafat"],
    createdDate: "2020-04-23T18:25:43.511Z",
    updateDate: "2020-05-01T14:35:43.511Z",
    priority: 2,
    isActive: true,
  },
  {
    id: 3,
    category: "İran",
    type: "news",
    caption: "İran'da ölü sayısı fena",
    summary: "Nolacak iranın hali derken olanlara bakkk",
    imgPath: "https://via.placeholder.com/600x300?text=IRAN",
    imgAlt: "test haber img",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi at nisi ex. Nullam et elit elementum, consequat risus ut, aliquet metus. Phasellus pharetra, urna non mollis auctor, dui erat fermentum lorem, sed egestas sem nisl ut augue. Duis vitae turpis non dui luctus congue. Donec iaculis, diam in consequat dapibus, tortor mauris rhoncus ex, sit amet rutrum augue arcu a lacus. Vestibulum porta, orci vitae ultrices blandit, dolor metus tristique lorem, eget placerat nisl nulla in turpis. Maecenas vel aliquam leo. Vivamus eleifend sapien vel mauris mollis imperdiet.",
    subjects: ["Covid", "Türkiye"],
    authors: ["Mustafa Çolakoğlu", "Burak Kalafat"],
    createdDate: "2020-04-23T18:25:43.511Z",
    updateDate: "2020-05-01T14:35:43.511Z",
    priority: 3,
    isActive: true,
  },
  {
    id: 4,
    category: "Magazin",
    type: "news",
    caption: "Cem ve Setenay",
    summary: "Okey oynadılar",
    imgPath: "https://via.placeholder.com/600x300?text=HABER 4",
    imgAlt: "test haber img",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi at nisi ex. Nullam et elit elementum, consequat risus ut, aliquet metus. Phasellus pharetra, urna non mollis auctor, dui erat fermentum lorem, sed egestas sem nisl ut augue. Duis vitae turpis non dui luctus congue. Donec iaculis, diam in consequat dapibus, tortor mauris rhoncus ex, sit amet rutrum augue arcu a lacus. Vestibulum porta, orci vitae ultrices blandit, dolor metus tristique lorem, eget placerat nisl nulla in turpis. Maecenas vel aliquam leo. Vivamus eleifend sapien vel mauris mollis imperdiet.",
    subjects: ["Covid", "Türkiye"],
    authors: ["Mustafa Çolakoğlu", "Burak Kalafat"],
    createdDate: "2020-04-23T18:25:43.511Z",
    updateDate: "2020-05-01T14:35:43.511Z",
    priority: 4,
    isActive: true,
  },
  {
    id: 5,
    category: "Covid",
    type: "news",
    caption: "Korona vaka sayısı",
    summary: "Haberim yoktu",
    imgPath: "https://via.placeholder.com/600x300?text=HABER 5",
    imgAlt: "test haber img",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi at nisi ex. Nullam et elit elementum, consequat risus ut, aliquet metus. Phasellus pharetra, urna non mollis auctor, dui erat fermentum lorem, sed egestas sem nisl ut augue. Duis vitae turpis non dui luctus congue. Donec iaculis, diam in consequat dapibus, tortor mauris rhoncus ex, sit amet rutrum augue arcu a lacus. Vestibulum porta, orci vitae ultrices blandit, dolor metus tristique lorem, eget placerat nisl nulla in turpis. Maecenas vel aliquam leo. Vivamus eleifend sapien vel mauris mollis imperdiet.",
    subjects: ["Covid", "Türkiye"],
    authors: ["Mustafa Çolakoğlu", "Burak Kalafat"],
    createdDate: "2020-04-23T18:25:43.511Z",
    updateDate: "2020-05-01T14:35:43.511Z",
    priority: 5,
    isActive: true,
  },
  {
    id: 6,
    category: "Covid",
    type: "news",
    caption: "Korona vaka sayısı",
    summary: "Türkiyede vaka sayısı azalıyor.",
    imgPath: "https://via.placeholder.com/600x300?text=KORONA",
    imgAlt: "test haber img",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi at nisi ex. Nullam et elit elementum, consequat risus ut, aliquet metus. Phasellus pharetra, urna non mollis auctor, dui erat fermentum lorem, sed egestas sem nisl ut augue. Duis vitae turpis non dui luctus congue. Donec iaculis, diam in consequat dapibus, tortor mauris rhoncus ex, sit amet rutrum augue arcu a lacus. Vestibulum porta, orci vitae ultrices blandit, dolor metus tristique lorem, eget placerat nisl nulla in turpis. Maecenas vel aliquam leo. Vivamus eleifend sapien vel mauris mollis imperdiet.",
    subjects: ["Covid", "Türkiye"],
    authors: ["Mustafa Çolakoğlu", "Burak Kalafat"],
    createdDate: "2020-04-23T18:25:43.511Z",
    updateDate: "2020-05-01T14:35:43.511Z",
    priority: 6,
    isActive: true,
  },
  {
    id: 7,
    category: "Covid",
    type: "news",
    caption: "Korona vaka sayısı",
    summary: "Türkiyede vaka sayısı azalıyor.",
    imgPath: "https://via.placeholder.com/600x300?text=KORONA",
    imgAlt: "test haber img",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi at nisi ex. Nullam et elit elementum, consequat risus ut, aliquet metus. Phasellus pharetra, urna non mollis auctor, dui erat fermentum lorem, sed egestas sem nisl ut augue. Duis vitae turpis non dui luctus congue. Donec iaculis, diam in consequat dapibus, tortor mauris rhoncus ex, sit amet rutrum augue arcu a lacus. Vestibulum porta, orci vitae ultrices blandit, dolor metus tristique lorem, eget placerat nisl nulla in turpis. Maecenas vel aliquam leo. Vivamus eleifend sapien vel mauris mollis imperdiet.",
    subjects: ["Covid", "Türkiye"],
    authors: ["Mustafa Çolakoğlu", "Burak Kalafat"],
    createdDate: "2020-04-23T18:25:43.511Z",
    updateDate: "2020-05-01T14:35:43.511Z",
    priority: 7,
    isActive: true,
  },
  {
    id: 8,
    category: "Covid",
    type: "news",
    caption: "Korona vaka sayısı",
    summary: "Türkiyede vaka sayısı azalıyor.",
    imgPath: "https://via.placeholder.com/600x300?text=KORONA",
    imgAlt: "test haber img",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi at nisi ex. Nullam et elit elementum, consequat risus ut, aliquet metus. Phasellus pharetra, urna non mollis auctor, dui erat fermentum lorem, sed egestas sem nisl ut augue. Duis vitae turpis non dui luctus congue. Donec iaculis, diam in consequat dapibus, tortor mauris rhoncus ex, sit amet rutrum augue arcu a lacus. Vestibulum porta, orci vitae ultrices blandit, dolor metus tristique lorem, eget placerat nisl nulla in turpis. Maecenas vel aliquam leo. Vivamus eleifend sapien vel mauris mollis imperdiet.",
    subjects: ["Covid", "Türkiye"],
    authors: ["Mustafa Çolakoğlu", "Burak Kalafat"],
    createdDate: "2020-04-23T18:25:43.511Z",
    updateDate: "2020-05-01T14:35:43.511Z",
    priority: 8,
    isActive: true,
  },
  {
    id: 9,
    category: "Covid",
    type: "news",
    caption: "Korona vaka sayısı",
    summary: "Türkiyede vaka sayısı azalıyor.",
    imgPath: "https://via.placeholder.com/600x300?text=KORONA",
    imgAlt: "test haber img",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi at nisi ex. Nullam et elit elementum, consequat risus ut, aliquet metus. Phasellus pharetra, urna non mollis auctor, dui erat fermentum lorem, sed egestas sem nisl ut augue. Duis vitae turpis non dui luctus congue. Donec iaculis, diam in consequat dapibus, tortor mauris rhoncus ex, sit amet rutrum augue arcu a lacus. Vestibulum porta, orci vitae ultrices blandit, dolor metus tristique lorem, eget placerat nisl nulla in turpis. Maecenas vel aliquam leo. Vivamus eleifend sapien vel mauris mollis imperdiet.",
    subjects: ["Covid", "Türkiye"],
    authors: ["Mustafa Çolakoğlu", "Burak Kalafat"],
    createdDate: "2020-04-23T18:25:43.511Z",
    updateDate: "2020-05-01T14:35:43.511Z",
    priority: 9,
    isActive: true,
  },
  {
    id: 10,
    category: "Covid",
    type: "news",
    caption: "Korona vaka sayısı",
    summary: "Türkiyede vaka sayısı azalıyor.",
    imgPath: "https://via.placeholder.com/600x300?text=KORONA",
    imgAlt: "test haber img",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi at nisi ex. Nullam et elit elementum, consequat risus ut, aliquet metus. Phasellus pharetra, urna non mollis auctor, dui erat fermentum lorem, sed egestas sem nisl ut augue. Duis vitae turpis non dui luctus congue. Donec iaculis, diam in consequat dapibus, tortor mauris rhoncus ex, sit amet rutrum augue arcu a lacus. Vestibulum porta, orci vitae ultrices blandit, dolor metus tristique lorem, eget placerat nisl nulla in turpis. Maecenas vel aliquam leo. Vivamus eleifend sapien vel mauris mollis imperdiet.",
    subjects: ["Covid", "Türkiye"],
    authors: ["Mustafa Çolakoğlu"],
    createdDate: "2020-04-23T18:25:43.511Z",
    updateDate: "2020-05-01T14:35:43.511Z",
    priority: 10,
    isActive: true,
  },
  {
    id: 11,
    category: "Pasif test",
    type: "news",
    caption: "İptal edilen haber",
    summary: "Silinmesi gerekirdi",
    imgPath: "https://via.placeholder.com/600x300?text=KORONA",
    imgAlt: "test haber img",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi at nisi ex. Nullam et elit elementum, consequat risus ut, aliquet metus. Phasellus pharetra, urna non mollis auctor, dui erat fermentum lorem, sed egestas sem nisl ut augue. Duis vitae turpis non dui luctus congue. Donec iaculis, diam in consequat dapibus, tortor mauris rhoncus ex, sit amet rutrum augue arcu a lacus. Vestibulum porta, orci vitae ultrices blandit, dolor metus tristique lorem, eget placerat nisl nulla in turpis. Maecenas vel aliquam leo. Vivamus eleifend sapien vel mauris mollis imperdiet.",
    subjects: ["Covid", "Türkiye"],
    authors: ["Mustafa Çolakoğlu", "Burak Kalafat"],
    createdDate: "2020-04-23T18:25:43.511Z",
    updateDate: "2020-05-01T14:35:43.511Z",
    priority: 11,
    isActive: false,
  },
  {
    id: 12,
    category: "Süper Lig",
    type: "subNews",
    caption: "Trabzonspor'un liderliği tescillenecek.",
    summary: "Her ligde olduğu gibi trabzonspor'un da liderliği tescillendi.",
    imgPath: "https://via.placeholder.com/384x216/000000/FFFFFF/?text=TRABZONSPOR_IMG",
    imgAlt: "test haber img",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi at nisi ex. Nullam et elit elementum, consequat risus ut, aliquet metus. Phasellus pharetra, urna non mollis auctor, dui erat fermentum lorem, sed egestas sem nisl ut augue. Duis vitae turpis non dui luctus congue. Donec iaculis, diam in consequat dapibus, tortor mauris rhoncus ex, sit amet rutrum augue arcu a lacus. Vestibulum porta, orci vitae ultrices blandit, dolor metus tristique lorem, eget placerat nisl nulla in turpis. Maecenas vel aliquam leo. Vivamus eleifend sapien vel mauris mollis imperdiet.",
    subjects: ["Covid", "Türkiye"],
    authors: ["Mustafa Çolakoğlu", "Burak Kalafat"],
    createdDate: "2020-04-23T18:25:43.511Z",
    updateDate: "2020-05-01T14:35:43.511Z",
    priority: 12,
    isActive: true,
  },
  {
    id: 13,
    category: "Lokal",
    type: "subNews",
    caption: "Sürmene'de sessizlik hakim",
    summary: "Sürmene evde kalıyor",
    imgPath: "https://via.placeholder.com/384x216/000000/FFFFFF/?text=SÜRMENE_IMG",
    imgAlt: "test haber img",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi at nisi ex. Nullam et elit elementum, consequat risus ut, aliquet metus. Phasellus pharetra, urna non mollis auctor, dui erat fermentum lorem, sed egestas sem nisl ut augue. Duis vitae turpis non dui luctus congue. Donec iaculis, diam in consequat dapibus, tortor mauris rhoncus ex, sit amet rutrum augue arcu a lacus. Vestibulum porta, orci vitae ultrices blandit, dolor metus tristique lorem, eget placerat nisl nulla in turpis. Maecenas vel aliquam leo. Vivamus eleifend sapien vel mauris mollis imperdiet.",
    subjects: ["Covid", "Türkiye"],
    authors: ["Mustafa Çolakoğlu"],
    createdDate: "2020-04-23T18:25:43.511Z",
    updateDate: "2020-05-01T14:35:43.511Z",
    priority: 13,
    isActive: true,
  },
  {
    id: 14,
    category: "Alt Haber 3",
    type: "subNews",
    caption: "Alt'ta görünen haberlederden 3.sü",
    summary: "bu haberi görenler şokta",
    imgPath: "https://via.placeholder.com/384x216/000000/FFFFFF/?text=ALT+HABER+3_IMG",
    imgAlt: "test haber img",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi at nisi ex. Nullam et elit elementum, consequat risus ut, aliquet metus. Phasellus pharetra, urna non mollis auctor, dui erat fermentum lorem, sed egestas sem nisl ut augue. Duis vitae turpis non dui luctus congue. Donec iaculis, diam in consequat dapibus, tortor mauris rhoncus ex, sit amet rutrum augue arcu a lacus. Vestibulum porta, orci vitae ultrices blandit, dolor metus tristique lorem, eget placerat nisl nulla in turpis. Maecenas vel aliquam leo. Vivamus eleifend sapien vel mauris mollis imperdiet.",
    subjects: ["Covid", "Türkiye"],
    authors: ["Mustafa Çolakoğlu", "Burak Kalafat"],
    createdDate: "2020-04-23T18:25:43.511Z",
    updateDate: "2020-05-01T14:35:43.511Z",
    priority: 14,
    isActive: true,
  },
  {
    id: 15,
    category: "Alt Haber 4",
    type: "subNews",
    caption: "İptal edilen haber",
    summary: "Silinmesi gerekirdi",
    imgPath: "https://via.placeholder.com/384x216/000000/FFFFFF/?text=ALT+HABER+4_IMG",
    imgAlt: "test haber img",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi at nisi ex. Nullam et elit elementum, consequat risus ut, aliquet metus. Phasellus pharetra, urna non mollis auctor, dui erat fermentum lorem, sed egestas sem nisl ut augue. Duis vitae turpis non dui luctus congue. Donec iaculis, diam in consequat dapibus, tortor mauris rhoncus ex, sit amet rutrum augue arcu a lacus. Vestibulum porta, orci vitae ultrices blandit, dolor metus tristique lorem, eget placerat nisl nulla in turpis. Maecenas vel aliquam leo. Vivamus eleifend sapien vel mauris mollis imperdiet.",
    subjects: ["Covid", "Türkiye"],
    authors: ["Mustafa Çolakoğlu", "Burak Kalafat"],
    createdDate: "2020-04-23T18:25:43.511Z",
    updateDate: "2020-05-01T14:35:43.511Z",
    priority: 15,
    isActive: true,
  },
  {
    id: 16,
    category: "Alt Haber 5",
    type: "subNews",
    caption: "Bu iyi haber",
    summary: "Silinmesi gerekirdi",
    imgPath: "https://via.placeholder.com/384x216/000000/FFFFFF/?text=ALT+HABER+5_IMG",
    imgAlt: "test haber img",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi at nisi ex. Nullam et elit elementum, consequat risus ut, aliquet metus. Phasellus pharetra, urna non mollis auctor, dui erat fermentum lorem, sed egestas sem nisl ut augue. Duis vitae turpis non dui luctus congue. Donec iaculis, diam in consequat dapibus, tortor mauris rhoncus ex, sit amet rutrum augue arcu a lacus. Vestibulum porta, orci vitae ultrices blandit, dolor metus tristique lorem, eget placerat nisl nulla in turpis. Maecenas vel aliquam leo. Vivamus eleifend sapien vel mauris mollis imperdiet.",
    subjects: ["Covid", "Türkiye"],
    authors: ["Mustafa Çolakoğlu", "Burak Kalafat"],
    createdDate: "2020-04-23T18:25:43.511Z",
    updateDate: "2020-05-01T14:35:43.511Z",
    priority: 15,
    isActive: true,
  },
  {
    id: 17,
    category: "Alt Haber 6",
    type: "subNews",
    caption: "En son haber",
    summary: "Neler oldu neler",
    imgPath: "https://via.placeholder.com/384x216/000000/FFFFFF/?text=ALT+HABER+6_IMG",
    imgAlt: "test haber img",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi at nisi ex. Nullam et elit elementum, consequat risus ut, aliquet metus. Phasellus pharetra, urna non mollis auctor, dui erat fermentum lorem, sed egestas sem nisl ut augue. Duis vitae turpis non dui luctus congue. Donec iaculis, diam in consequat dapibus, tortor mauris rhoncus ex, sit amet rutrum augue arcu a lacus. Vestibulum porta, orci vitae ultrices blandit, dolor metus tristique lorem, eget placerat nisl nulla in turpis. Maecenas vel aliquam leo. Vivamus eleifend sapien vel mauris mollis imperdiet.",
    subjects: ["Covid", "Türkiye"],
    authors: ["Mustafa Çolakoğlu", "Burak Kalafat"],
    createdDate: "2020-04-23T18:25:43.511Z",
    updateDate: "2020-05-01T14:35:43.511Z",
    priority: 15,
    isActive: true,
  },
];

export default newsList;